title: Jun Poh # your name (or website title) here
logo: "/images/head_shot.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>
  <strong>Data Scientist & AI Product Strategist | Ex-McDonald</strong>
  <br>
  I leverage data to drive high-stakes decision-making and product strategy. With 4+ years of experience across analytics and research, I specialize in translating complex datasets into actionable business roadmaps. 
  <br><br>
  My approach combines forensic data analysis with a product mindset to solve critical operational challenges and identify growth opportunities. Whether it’s navigating nationwide service disruptions or rapid-prototyping AI solutions, I bridge the gap between technical complexity and executive-level strategy.
  <br><br>
  <strong>Work Experience:</strong>
  <br>
  Strategy and Insights Consultant | McDonald's Australia
  <br><br>
  <strong>Education:</strong>
  <br> 
  Msc Data Science (Distinction), University of Sydney
  <br><br>
  BS Electrical and Electronics Engineering, RMIT University
  <br><br>
  <a href="https://www.linkedin.com/in/junpoh/">View my LinkedIn Profile</a> 
  <br> 
  <a href="https://github.com/junpohw/">View my GitHub Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'

